# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f4836834987a5e1a313b26d5e60402d58dcd7e4c8e996ec78dbb1f7893946e9fdd644d47f55e20b8ba7438b67b9b0097260ffe2dccc801df3c9441bc62f5e65

test:
  secret_key_base: 12fbcc4088faa15385e61d54c4fe13b50318da819ab3818a3d5a4a19f7e92564ccc09c80e4c968d8194ee34f6e274d3b1b2063b0fefbe129866caecc9c00bfb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
